### ISSUE TITLE
gap

### ISSUE THREAD

**Issue by aweibell** [shinriyo/breeze#10]
Thank you very much for providing this!

I miss the `gap` command, though! It don't work with `ga --patch` either. I assume you might add more in the coming days, as it seems you just recently started on this :)

**Comment by shinriyo** [comment]
thank you for using.
The product is working on progress.
But I WILL add all of scm_breeze.
And 'ga' command also

**Comment by shinriyo** [comment]
I added `ga` command.
`fisher up breeze`

**Comment by shinriyo** [comment]
@aweibell 
Did you update?

**Comment by shinriyo** [comment]
aaa

**Comment by aweibell** [comment]
Yes. It worked well with gap, but the lack of extra params is still a minus
compared to the original.

Den søn. 5. feb. 2017, 07.06 skrev shinriyo <notifications@github.com>:
