### ISSUE TITLE
gs lacks parsing of all short-hand permutations

### ISSUE THREAD

**Issue by rsa2135** [shinriyo/breeze#30]
### Issue description
Currently `gs` only covers a handful (of the more common) status permutation that can occur between the working tree and the index. Specifically, `??`, ` M`, ` M`, `MM`, `D`, ` D`, `DD`, `R`, ` A`, and `A `.
For all other short-hand permutations, an error is printed to the screen— `TODO: UNKNOWN. FIX LATER...`
Furthermore, many of the parsed statuses will not appear in all relevant states (to be committed, and not staged), but only in one.

### Steps to reproduce the issue

1. Bring a file in your current branch to a permutation that is not supported. 
For example, a `git status --porcelain` output of `AD added to index, deleted in tree.txt.txt` and then 

2. run `gs`

### What's the expected result?
```
➤ Changes to be committed:

#        new file:  [1] added to index, deleted in tree.txt

➤ Changes not staged for commit:

#         deleted: [2] added to index, deleted in tree.txt
```

### What's the actual result?
```
➤ Changes to be committed:

AD "added to index, deleted in tree.txt"
TODO: UNKNOWN. FIX LATER...
```

### Additional details / screenshot
Here's an example of an output the shows quite a few of these issues
<img width="883" alt="before" src="https://user-images.githubusercontent.com/16783217/79820563-8df28d00-835a-11ea-8528-e590a039ec80.png">

**Comment by rsa2135** [comment]
Would love to contribute, but I'm getting 403 when trying to push. Is the error on my end or is is the repo currently on read-only mode?

**Comment by jdelStrother** [comment]
If you fork it and submit a pull request I can merge it in.

**Comment by shinriyo** [comment]
> or is is the repo currently on read-only mode?

No it isn't 

thank you for your contributed

**Comment by rsa2135** [comment]
Hey, I linked a PR. Here's a screenshot of `gs`s output on the same change list as the output above.
<img width="1010" alt="after" src="https://user-images.githubusercontent.com/16783217/79931302-b9d44800-8418-11ea-81f3-cf3837bb5923.png">
