### ISSUE TITLE
Consider converting simple aliases to abbreviations

### ISSUE THREAD

**Issue by bingocaller** [shinriyo/breeze#41]
## What?
Since fish supports [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html), perhaps we should convert the simple aliases (like `gf` for `git fetch`) to abbreviations?  
For example, with an abbreviation in place, the input <kbd>g</kbd> <kbd>f</kbd> <kbd>Space</kbd> will result in the full text `git fetch ` on the command line; from here the user can keep typing to append stuff to the command. Alternatively, if the user ends the abbreviation with <kbd>Enter</kbd>, the full text gets unfolded and the command is issued immediately.

## Why?
1. I think this would be helpful for users to see which git commands are actually being run and also make command history more searchable (it's probably easier to remember to search for `git rebase` rather than `grb`).
2. We don't flood the user's `functions` directory with non-namespaced functions.
3. It might eliminate the need for custom completions.
4. See more pros and cons in fish-shell/fish-shell#731

## However!
Depending on how we handle it, this might be a breaking change if people use their breeze aliases inside functions or other aliases.

Also, I'm not entirely sure how to get this to the users since each abbreviation is stored as a global or universal variable and not as a function. Maybe we can add it in a `conf.d` script which runs as part of the `fisher` install process?

**Comment by bingocaller** [comment]
@shinriyo Should I give this a stab? I can provide a PR, which might help clarify what this change will mean for the project.

**Comment by shinriyo** [comment]
@bingocaller Thank you for your pullrequest.

**Comment by shinriyo** [comment]
@bingocaller

 Hello, can you run `gs` command?

```
_breeze_git_branch
fish: Unknown command _breeze_git_branch
```

So, I reopened the issue.

**Comment by bingocaller** [comment]
@shinriyo Yes, it works for me. I'm on the latest version of shinriyo/breeze, installed through fisher.  
Maybe you're still installing from my branch or there are some leftover abbreviations in your config?  
Does `abbr --show | grep _breeze` give you any output? If so, you might have to run an `abbr --erase` command for each abbreviation you want to get rid of.

**Comment by shinriyo** [comment]
@bingocaller 

Thank you for replying. I didn't know `abbr` command.

I ran it.
```
> abbr --show | grep _breeze
abbr -a -U -- ga _breeze_git_add
abbr -a -U -- gb _breeze_git_branch
abbr -a -U -- gbl _breeze_git_blame
abbr -a -U -- gbu _breeze_git_branch_upstream
abbr -a -U -- gco _breeze_git_checkout
abbr -a -U -- gd _breeze_git_diff
abbr -a -U -- gl _breeze_git_log
abbr -a -U -- grm _breeze_git_rm
abbr -a -U -- gs _breeze_git_status
```

So, how do I use `abbr --erase` command?

**Comment by shinriyo** [comment]
I don't know what it is 😄 . but it may resove.

```
abbr --erase: No abbreviation named _breeze_git_add
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase ga
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gb
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gbl
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gbu
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gbo
abbr --erase: No abbreviation named gbo
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gd
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gl
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gco
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gl
abbr --erase: No abbreviation named gl
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase grm
shinriyo@Shinsukes-MBP ~/d/f/andu> abbr --erase gs
```

but, I wanted to know the one-liner remove command 👍

**Comment by bingocaller** [comment]
@shinriyo You would have to run `abbr --erase` for each abbreviation you want to erase, so `abbr --erase gs`, `abbr --erase gd`, etc. until they are all gone. 
You could potentially also create a one-liner, which chains together all the `abbr --erase` commands with `and` or `&&` like so: `abbr --erase gs; and abbr --erase gd ...` or `abbr --erase gs && abbr --erase gd ...`

**Comment by shinriyo** [comment]
@bingocaller 
putting gs and gd,  ... are troublesome.
I'd like to automatically collect them.

I didn't try it yet. but I guess like this

```
abbr --show | grep _breeze | awk -F'[ ]' '{print $5}' | xargs -n1 abbr --erase
```

**Comment by bingocaller** [comment]
@shinriyo Yeah, that could probably work! But I don't think it's a problem for other users than you and I, since we're the only ones (that I know of) who have tested the `_breeze_git` approach.

**Comment by shinriyo** [comment]
I forgot to close
